### PR TITLE
Update to Sufia 6.6.1

### PR DESCRIPTION
**Pull request by rotated8**
The new Gemfile.lock needs to be installed, then the server restarted.

### CODE REVIEW

**Comment by rotated8** [comment]
The optional portions of 6.4.0 were not applied: https://github.com/projecthydra/sufia/releases/tag/v6.4.0

**Comment by rotated8** [comment]
- Adds more gem updates
- Reorganizes JS to prevent errors
- Updates batchuser and audituser for CAS auth.
- Refactors tests to prevent errors from more than one request in a test
  block.

**Comment by rotated8** [comment]
Now includes Geonames configuration in secrets.yml

**Comment by pmather** [comment]
Verified OK in development mode. 👍

**Comment by pmather** [comment]
Verified OK in production mode. 👍

**Pull request merged**
