### PR TITLE
Fix LIBTD-286 as well as finish test examples for assign_doi job and …

### PR DESCRIPTION
**Pull request by tingtingjh**
…send_email mailer

Remove unnecessary pending example

Fixes could not find despositor issue in mailer examples

### CODE REVIEW

**Comment by yinlinchen** [comment]
+1  will merged it at 4pm if there is no other response.

**Comment by rotated8** [comment]
@yinlinchen please wait for @tonmoy18 to :+1: this.

**Comment by tonmoy18** [comment]
Seems good, but maybe in users factory "default_user" should create/find a user with email and return that user instead of returning the email as string.

**Comment by tonmoy18** [comment]
+1 I vote for merging

**Comment by rotated8** [comment]
@tonmoy18 The default_user change sounds good.

**Comment by rotated8** [comment]
@tonmoy18 The default_user change sounds good. @tingtingjh, how hard would that be to incorporate?

**Comment by tonmoy18** [comment]
Well, Sufia is returning strings too. So I now think it might be an acceptable practice.

**Comment by rotated8** [comment]
Ok, nevermind, then.

**Pull request merged**
