### PR TITLE
Fixed funder jquery validator parenthesis issue

### PR DESCRIPTION
**Pull request by tonmoy18**
LIBTD-256

### CODE REVIEW

**Comment by yinlinchen** [comment]
Why #86 has this issue and been merged?

**Comment by tonmoy18** [comment]
There was syntax error on the merged PR.

**Comment by yinlinchen** [comment]
Please do check next time before your submit PR. Some tools might help. e.g. firebug

**Comment by tonmoy18** [comment]
Sorry, I should have tested again after removing the parenthesis.

**Pull request merged**
