### PR TITLE
New branding to comply w/ university re-design.

### PR DESCRIPTION
**Pull request by whunter**
new favicon

begin on masthead

new vt logo

git rid of swap file. oops

vt search bar and begin main dropdown nav

add fonts

fix fonts

main nav working

fix dropdown menu issue

header and footer

finish footer. page title

new colors. redesigned search

### CODE REVIEW

**Comment by pmather** [comment]
Do we have permission to use/distribute these fonts?

**Comment by whunter** [comment]
@pmather Yes, these fonts are available to download from University Relation's branding site and we were asked to try to implement the new header and footer styles (at minimum) in our sites, including the fonts.

**Comment by pmather** [comment]
Isn't the VT branding site behind a VT login (i.e., you need a valid VT PID to access the branding materials)?  However, in this commit, you are putting the materials up for public download.

There was a thread on VT's techsupport-g recently about creating a VT-branded Google Slides template that touches on these font concerns.  Marvin Addison's responses in the thread are very pertinent: he chose Proxima Nova as the closest substitute for Acherus Grotesque because the former is part of the Google Fonts project and is widely and freely available whereas Acherus Grotesque is not.

I am not trying to be a pain here.  I'm just trying to point out that you may be inadvertently distributing a copyrighted font in violation of its license.

**Comment by whunter** [comment]
I can see the concern with having them in the commit. I hadn't thought about that. Could we alternatively put them in the local_files directory and copy them into the appropriate folder via rake task? That should allow us to remove them from git tracking.

**Pull request closed without merging**
