### PR TITLE
Fixed concurrent ajax search issue

### PR DESCRIPTION
**Pull request by tonmoy18**

### CODE REVIEW

**Comment by yinlinchen** [comment]
Please indicate/create which JIRA ticket belong to this issue.

**Comment by tonmoy18** [comment]
JIRA Ticket: LIBTD-223

**Comment by yinlinchen** [comment]
There are source code duplication in #74 and #72, can you develop function in order to reduce that?

**Comment by tonmoy18** [comment]
I created the branch for #74 from the branch for #72. I think there is no actual code duplication.

**Comment by yinlinchen** [comment]
Please merged LIBTD-223 and LIBTD-222 into one JIRA ticket and merged changes in #74 and #72 into one PR.

**Comment by tonmoy18** [comment]
LIBTD-223 and LIBTD-222 is merged into LIBTD-223
This pull request is merged with #72

**Comment by rotated8** [comment]
:+1:

**Pull request merged**
