### PR TITLE
When creating a new admin user with rake task, should not echo the pa…

### PR DESCRIPTION
**Pull request by tingtingjh**
…ssword on the screen. Fix LIBTD-110.

### CODE REVIEW

**Comment by pmather** [comment]
Arguably, the rake task should just set a default Admin username and password, which the real Admin can then change in the application.  (This is how most applications do it.)  It may be that with the removal of the local database auth that it's no longer possible to change passwords.  In that case, this approach is okay, although it would be nice to pass in the username and password as arguments to the rake task.  (See, e.g., http://stackoverflow.com/questions/825748/how-do-i-pass-command-line-arguments-to-a-rake-task)

Scripting keyboard input is not as convenient as using command-line arguments.  (I have been doing this step using here documents.)

**Comment by tingtingjh** [comment]
Now instead of prompting for a random admin user's email and password, default email and password are set up through the rake task.

**Comment by rotated8** [comment]
I'm :+1:, @pmather ?

**Comment by pmather** [comment]
:+1: from me, too, after chatting with Collin.

**Pull request merged**
