### PR TITLE
Add migrations to git.

### PR DESCRIPTION
**Pull request by rotated8**

### CODE REVIEW

**Comment by rotated8** [comment]
cc @pmather

**Comment by pmather** [comment]
I thought DB migrations were normally handled via a Rake task, e.g., this sort of workflow:

1: Pull down latest version of code ("svn update", "git pull", etc.)
2: Perform DB migrations ("rake db:migrate RAILS_ENV=production")

Is the above addition because some of the migrations are slightly edited from the automated defaults?

**Comment by rotated8** [comment]
That is the workflow that adding the migrations to git facilitates. The migrations describe the changes `rake db:migrate` will make to the database, along with the order to implement them. And by having the migrations in git, `git pull` will get any new migrations that are added to the branch.

**Comment by pmather** [comment]
Okay, thanks for clarifying.  That's :+1: from me, then.

**Comment by rotated8** [comment]
I'm going to revert this until I get the install script changes sorted out.

**Pull request merged**
