### PR TITLE
Fixed ui related issue for ED Lite

### PR DESCRIPTION
**Pull request by tonmoy18**
Fixed whitespace issues

Fixed more whitespace issues

### CODE REVIEW

**Comment by yinlinchen** [comment]
Please indicate/create which JIRA ticket belong to this issue.

**Comment by tonmoy18** [comment]
there is no ticket, it is a fix/modification for previous PR

**Comment by tonmoy18** [comment]
JIRA Ticket: LIBTD-222

**Comment by tonmoy18** [comment]
This does not need to be merged, the same code is present in #74

**Pull request closed without merging**
