### PR TITLE
Add DOD/DOE statement. LIBTD-200

### PR DESCRIPTION
**Pull request by yinlinchen**

### CODE REVIEW

**Comment by rotated8** [comment]
I don't think this covers what we were talking about on Wednesday. DOD/DOE are two cases where a user MIGHT have dissemination restrictions, but we also don't want anything with personally identifying information.

**Comment by yinlinchen** [comment]
@zhiwuxie  Please give final version

**Comment by pmather** [comment]
You could put, "Do not upload any OESRC-covered or sensitive material" and link "OESRC" to the Office of Export and Secure Research Compliance Web site (http://oesrc.researchcompliance.vt.edu/).  You could also link "sensitive data" to an appropriate page, e.g., the VT policy or the ITSO Web page on sensitive data (http://www.security.vt.edu/protectdata.html).  I am also assuming the aforementioned deposit agreement spells out clearly what we can and cannot take.

**Comment by zhiwuxie** [comment]
Discuss on Jira pls, not here.

**Comment by rotated8** [comment]
:+1:

**Pull request merged**
